import { COLORS } from "@/constants/theme";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#fff",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#000",
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
    },
    headerButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#f0f0f0",
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 8,
    },
    searchHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    searchBackButton: {
      marginRight: 12,
    },
    searchInputContainer: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#f0f0f0",
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
      marginLeft: 8,
      color: "#000",
    },
    activeUsersSection: {
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    activeUsersList: {
      paddingVertical: 12,
      paddingHorizontal: 16,
    },
    myStoryItem: {
      alignItems: "center",
      marginRight: 16,
      width: 70,
    },
    myStoryAvatarContainer: {
      position: "relative",
      marginBottom: 4,
    },
    myStoryAvatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
    },
    addStoryButton: {
      position: "absolute",
      bottom: 0,
      right: 0,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: COLORS.primary,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#fff",
    },
    myStoryText: {
      fontSize: 12,
      color: "#666",
      textAlign: "center",
    },
    activeUserItem: {
      alignItems: "center",
      marginRight: 16,
      width: 70,
    },
    activeUserAvatarContainer: {
      position: "relative",
      marginBottom: 4,
    },
    activeUserAvatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
      borderWidth: 2,
      borderColor: COLORS.primary,
    },
    onlineIndicator: {
      position: "absolute",
      bottom: 0,
      right: 0,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: "#4CAF50",
      borderWidth: 2,
      borderColor: "#fff",
    },
    activeUserName: {
      fontSize: 12,
      color: "#000",
      textAlign: "center",
    },
    conversationsList: {
      paddingTop: 8,
      paddingBottom: 80,
    },
    conversationItem: {
      flexDirection: "row",
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    conversationAvatarContainer: {
      position: "relative",
    },
    conversationAvatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
    },
    conversationOnlineIndicator: {
      position: "absolute",
      bottom: 0,
      right: 0,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: "#4CAF50",
      borderWidth: 2,
      borderColor: "#fff",
    },
    conversationContent: {
      flex: 1,
      marginLeft: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
      paddingBottom: 12,
    },
    conversationHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 4,
    },
    conversationName: {
      fontSize: 16,
      fontWeight: "500",
      color: "#000",
      flex: 1,
    },
    unreadName: {
      fontWeight: "bold",
    },
    conversationTime: {
      fontSize: 12,
      color: "#999",
    },
    unreadTime: {
      color: COLORS.primary,
      fontWeight: "bold",
    },
    conversationFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    conversationLastMessage: {
      fontSize: 14,
      color: "#666",
      flex: 1,
      marginRight: 8,
    },
    unreadMessage: {
      color: "#000",
      fontWeight: "500",
    },
    unreadBadge: {
      backgroundColor: COLORS.primary,
      borderRadius: 10,
      minWidth: 20,
      height: 20,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 6,
    },
    unreadBadgeText: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "bold",
    },
    groupMembersContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 6,
    },
    groupMemberBadge: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: "#f0f0f0",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#fff",
    },
    groupMemberText: {
      fontSize: 10,
      fontWeight: "bold",
      color: "#666",
    },
    groupMembersMore: {
      fontSize: 12,
      color: "#999",
      marginLeft: 4,
    },
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
    },
    emptyText: {
      fontSize: 16,
      color: "#999",
      marginTop: 12,
    },
    newMessageButton: {
      position: "absolute",
      right: 16,
      bottom: 80,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: COLORS.primary,
      justifyContent: "center",
      alignItems: "center",
      elevation: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    bottomNav: {
      flexDirection: "row",
      backgroundColor: "#fff",
      paddingTop: 8,
      paddingBottom: 24,
      borderTopWidth: 1,
      borderTopColor: "#f0f0f0",
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
    },
    navItem: {
      flex: 1,
      alignItems: "center",
    },
    navText: {
      fontSize: 12,
      marginTop: 4,
      color: "#666",
    },
    activeNavText: {
      color: COLORS.primary,
    },
  })
  export default styles;
  