import { COLORS } from "@/constants/theme";
import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F8F9FA",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      paddingVertical: 16,
      paddingHorizontal: 16,
    },
    backButton: {
      padding: 4,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: COLORS.dark,
    },
    coverPhotoContainer: {
      position: "relative",
      height: 200,
    },
    coverPhoto: {
      width: "100%",
      height: "100%",
    },
    profileAvatarContainer: {
      position: "absolute",
      bottom: -50,
      left: "50%",
      marginLeft: -50,
      borderRadius: 50,
      borderWidth: 4,
      borderColor: "#fff",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    profileAvatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
    },
    profileInfo: {
      marginTop: 60,
      alignItems: "center",
      paddingHorizontal: 16,
    },
    profileName: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#333",
    },
    profileBio: {
      fontSize: 16,
      color: "#666",
      textAlign: "center",
      marginTop: 8,
      marginBottom: 16,
      lineHeight: 22,
    },
    
    socialStats: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    socialStat: {
      alignItems: "center",
      paddingHorizontal: 20,
    },
    socialStatNumber: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
    },
    socialStatLabel: {
      fontSize: 14,
      color: "#666",
      marginTop: 4,
    },
    socialStatDivider: {
      width: 1,
      height: 24,
      backgroundColor: "#DDD",
    },
    profileActions: {
      flexDirection: "row",
      marginBottom: 16,
    },
    profileActionButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginHorizontal: 4,
    },
    primaryActionButton: {
      backgroundColor: COLORS.primary,
    },
    primaryActionText: {
      color: "#fff",
      fontWeight: "bold",
      marginLeft: 8,
    },
    secondaryActionButton: {
      backgroundColor: "#F0F2F5",
      borderWidth: 1,
      borderColor: COLORS.primary,
    },
    tabsContainer: {
      flexDirection: "row",
      backgroundColor: "#fff",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: "#DDD",
    },
    tab: {
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
    },
    activeTab: {
      borderBottomWidth: 2,
      borderBottomColor: COLORS.primary,
    },
    tabText: {
      fontSize: 14,
      color: "#666",
    },
    activeTabText: {
      color: COLORS.primary,
      fontWeight: "bold",
    },
    postsContainer: {
      padding: 16,
    },
    createPostCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 12,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    createPostHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    createPostAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
    },
    createPostInput: {
      flex: 1,
      backgroundColor: "#F0F2F5",
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    createPostPlaceholder: {
      color: "#666",
    },
    createPostActions: {
      flexDirection: "row",
      borderTopWidth: 1,
      borderTopColor: "#EEE",
      paddingTop: 12,
    },
    createPostAction: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    createPostActionText: {
      marginLeft: 4,
      fontSize: 14,
      color: "#666",
    },
    postCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      marginBottom: 16,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    postHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 12,
    },
    postUser: {
      flexDirection: "row",
      alignItems: "center",
    },
    postAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
    },
    postUserName: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
    },
    postTime: {
      fontSize: 12,
      color: "#666",
      marginTop: 2,
    },
    postContent: {
      fontSize: 14,
      color: "#333",
      lineHeight: 20,
      paddingHorizontal: 12,
      paddingBottom: 12,
    },
    postImage: {
      width: "100%",
      height: 300,
    },
    postStats: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: "#EEE",
    },
    postLikes: {
      flexDirection: "row",
      alignItems: "center",
    },
    likeIconContainer: {
      backgroundColor: COLORS.primary,
      width: 18,
      height: 18,
      borderRadius: 9,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 4,
    },
    statsText: {
      fontSize: 12,
      color: "#666",
    },
    postActions: {
      flexDirection: "row",
      paddingVertical: 8,
    },
    actionButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 4,
    },
    actionText: {
      fontSize: 14,
      color: "#666",
      marginLeft: 4,
    },
    aboutContainer: {
      padding: 16,
    },
    aboutCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    aboutTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 16,
    },
    aboutItem: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    aboutIcon: {
      marginRight: 12,
    },
    aboutLabel: {
      fontSize: 12,
      color: "#666",
    },
    aboutText: {
      fontSize: 14,
      color: "#333",
      fontWeight: "500",
    },
    aboutEditButton: {
      marginLeft: "auto",
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "#F0F2F5",
      justifyContent: "center",
      alignItems: "center",
    },
    interestsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 12,
    },
    interestTag: {
      backgroundColor: "#F0F2F5",
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginRight: 8,
      marginBottom: 8,
    },
    interestText: {
      fontSize: 14,
      color: "#333",
    },
    addInterestButton: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
    },
    addInterestText: {
      fontSize: 14,
      color: COLORS.primary,
      marginLeft: 4,
    },
    bottomNav: {
      flexDirection: "row",
      backgroundColor: "#fff",
      paddingTop: 8,
      paddingBottom: 24,
      borderTopWidth: 1,
      borderTopColor: "#E4E6EB",
    },
    navItem: {
      flex: 1,
      alignItems: "center",
    },
    navText: {
      fontSize: 12,
      marginTop: 4,
      color: "#65676B",
    },
    activeNavText: {
      color: COLORS.primary,
    },
  })
  export default styles;